CREATE TABLE UTENTE (
    USERNAME      VARCHAR(64) PRIMARY KEY,
    PASSWORD      VARCHAR(256) NOT NULL,
    NOME          VARCHAR(16) NOT NULL,
    COGNOME       VARCHAR(16) NOT NULL,
    DATANASCITA   DATE NOT NULL,
    SESSO         CHAR(1),
    NTEL          CHAR(10),
    RUOLO         VARCHAR(5)
);

CREATE TABLE PRODOTTOACQUISTABILE (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    PREZZO_BASE   DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    SCONTO        INT,
    PREZZO_SCONTATO   DECIMAL(6,2) NOT NULL,
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_PA_UTENTE_1
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);

CREATE TABLE CARRELLO (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    PREZZO_BASE   DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    SCONTO        INT,
    PREZZO_SCONTATO   DECIMAL(6,2) NOT NULL,
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_PA_UTENTE_2
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);

CREATE TABLE PRODOTTOACQUISTATO (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    PREZZO_BASE   DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    SCONTO        INT,
    PREZZO_SCONTATO   DECIMAL(6,2) NOT NULL,
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_PA_UTENTE_3
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);
