CREATE TABLE UTENTE (
    USERNAME      VARCHAR(64) PRIMARY KEY,
    PASSWORD      VARCHAR(256) NOT NULL,
    NOME          VARCHAR(16) NOT NULL,
    COGNOME       VARCHAR(16) NOT NULL,
    DATANASCITA   DATE NOT NULL,
    SESSO         CHAR(1),
    NTEL          CHAR(10),
    EMAIL         VARCHAR(80)
);

CREATE TABLE AMMINISTRATORE (
    USERNAME      VARCHAR(64) PRIMARY KEY,
    PASSWORD      VARCHAR(256) NOT NULL,
    NOME          VARCHAR(16) NOT NULL,
    COGNOME       VARCHAR(16) NOT NULL,
    DATANASCITA   DATE NOT NULL,
    SESSO         CHAR(1),
    NTEL          CHAR(10),
    EMAIL         VARCHAR(80)
);

CREATE TABLE PRODOTTOACQUISTABILE (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    COSTO         DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_PA_UTENTE
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);

CREATE TABLE CARRELLO (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    COSTO         DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_CARRELLO_UTENTE
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);

CREATE TABLE PRODOTTOACQUISTATO (
    CODICE        CHAR(4) PRIMARY KEY,
    NOME          VARCHAR(16) NOT NULL,
    DESCRIZIONE   VARCHAR(256),
    QUANTITA      INT NOT NULL,
    COSTO         DECIMAL(6,2) NOT NULL,
    CATEGORIA     VARCHAR(32),
    USERNAME      VARCHAR(64) NOT NULL,

    CONSTRAINT FK_PACQ_UTENTE
        FOREIGN KEY (USERNAME)
            REFERENCES UTENTE(USERNAME)
);
